apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: web
  namespace: commit-msg
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - commit-msg.durak.dev
      secretName: web-tls
  rules:
    - host: commit-msg.durak.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: web
                port:
                  number: 80
